FROM golang:1.23.6-alpine3.21

ARG COMMAND

ENV binary $COMMAND

RUN addgroup -g 1000 -S appgroup \
  && adduser -u 1000 -S appuser -G appgroup

WORKDIR /go/bin

COPY ${COMMAND} ./
COPY lib/*.go ./lib/
COPY lib/templates/ ./lib/templates/
COPY lib/static/* ./lib/static/
COPY utils/*.go ./utils/

USER 1000

EXPOSE 8080

CMD ["sh", "-c", "${binary}"]