ingress:
  hostname: reports.cloud-platform.service.justice.gov.uk
  name: cloud-platform-reports-app-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "cloud-platform-reports-app-ingress-new-cloud-platform-reports-prod-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=webops"
      SecDefaultAction "phase:4,pass,log,tag:github_team=webops"
  ingressClassName: modsec

ruby_service:
  name: cloud-platform-reports-service
  port: 4567

go_service:
  name: cloud-platform-reports-service-go
  port: 8080

ruby_deployment:
  replicas: 1
  name: cloud-platform-reports
  labels:
    app: cloud-platform-reports-app
  containers:
    webapp:
      name: cloud-platform-reports
      image: ministryofjustice/cloud-platform-how-out-of-date-are-we

go_deployment:
  replicas: 1
  name: cloud-platform-reports-go
  labels:
    app: cloud-platform-reports-app-go
  containers:
    webapp:
      name: cloud-platform-reports-go
      image: ministryofjustice/cloud-platform-how-out-of-date-are-we-go

dynamodb:
  secretName: cloud-platform-reports-dynamodb-output
